/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookTransactionResponse {
  author?: string;
  bookId?: number;
  isbn?: string;
  returnApproved?: boolean;
  returned?: boolean;
  title?: string;
}
