/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookTransactionResponse } from '../models/book-transaction-response';
export interface PageResponseBookTransactionResponse {
  contents?: Array<BookTransactionResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
